### ISSUE TITLE
Tutorial or Quickstart?

### ISSUE THREAD

**Issue by krambox** [measuresforjustice/textricator#11]
Does anyone know a tutorial to get started or a few more (but simpler examples) for yaml files? I'm having a hard time right now. For example, I want to extract a number from a PDF form in exactly one position.

**Comment by stephenbyrne-mfj** [comment]
If you can share your PDF form, or a redacted/modified version of it, I can write a yaml and add it to the examples.

**Comment by alvinets** [comment]
Can help to write a yaml example for below PDF?
[Sample_Certificate.pdf](https://github.com/measuresforjustice/textricator/files/6235358/Sample_Certificate.pdf)
Want to extract 3 fields:
1) Name (i.e. Alvin Lam)
2) Course Name (i.e. Get Ready: Club Public Image Committee )
3) Completion Date (i.e. 5/25/20)

**Comment by eabase** [comment]
@stephenbyrne-mfj 
I've added some stuff in issue #19. Maybe you can use that, if we can get it working.

**Comment by stephenbyrne-mfj** [comment]
For `Sample_Certificate.pdf`:

```yaml
---
extractor: "pdf.itext5"

header:
  default: 200 # Ignore the "Learning and Development" portion
footer:
  default: 500

maxRowDistance: 2

rootRecordType: certificate
recordTypes:
  certificate:
    label: "Certificate"
    valueTypes:
      - name
      - course
      - date

valueTypes:
  name:
    label: "Name"
  course:
    label: "Course Name"
  date:
    label: "Completion Date"
    # strip out the "on " before the date
    replacements:
      -
        pattern: "on\ *(.*)"
        replacement: "$1"

initialState: "INIT"

states:
  INIT:
    transitions:
      -
        condition: certifiesThat
        nextState: certifiesThat

  certifiesThat:
    include: false
    transitions:
      -
        condition: any
        nextState: name

  name:
    transitions:
      -
        condition: hasSuccessfullyCompleted
        nextState: hasSuccessfullyCompleted
      -
        condition: any
        nextState: name

  hasSuccessfullyCompleted:
    include: false
    transitions:
      -
        condition: any
        nextState: course

  course:
    transitions:
      -
        condition: date
        nextState: date
      -
        condition: any
        nextState: course

  date:
    transitions:
      -
        condition: certifiesThat
        nextState: certifiesThat

conditions:

  any: '1 = 1'

  certifiesThat: 'text = "Certifies that"'

  hasSuccessfullyCompleted: 'text = "has successfully completed"'

  date: 'text =~ /on .*/ and fontSize = 14.0'
```

Generates:

```csv
page,Name,Course Name,Completion Date
1,Alvin Lam,Get Ready: Club Public Image Committee,5/25/20
```
