### ISSUE TITLE
Help.

### ISSUE THREAD

**Issue by Gitme76269** [measuresforjustice/textricator#14]
I am stuck on a compile error, and not sure how to move forward.

Here is a clip from what I am trying to parse:
[ChaseTestss.pdf](https://github.com/measuresforjustice/textricator/files/5741951/ChaseTestss.pdf)

This is the YML I am writing
---
extractor: "pdf.pdfbox"

# All measurements are in points. 1 point = 1/72 of an inch.
# x-coordinates are from the left edge of the page.
# y-coordinates are from the top edge of the page.
header:
  default: 108
footer:
   default: 990

maxRowDistance: 2

# Define the output data record.

rootRecordType: date
recordTypes:
  date:
    label: "date"
    valueTypes:
      - date
      - description
      - order_number
      - amount

valueTypes:
  date:
    # In the CSV, use "Employee ID" as the column header instead of "employee".
    label: "Date"
  description:
    label: "Description"
  order_number:
    label: "Order Number"
  amount:
    label: "Amount"
 
# Now we define the finite-state machine
# Let's name the state that our machine starts off with:
initialState: "INIT"

# When each text segment is encountered, each transition for the current state is checked.
states:
  INIT:
    transitions:
     -
        condition: date
        nextState: date
      
  date:
#    startRecord: true # When we enter this stage, we'll create a new "case" record.
    transitions:
      -
        condition: description
        nextState: description  

  description:
    transitions:
    -
    condition: description
    nextState: description
    -
    condition: amount
    nextState: amount
    
  amount:
    transitions:
     -
     condition: date
     nextState: date
     -
     condition: order_number
     nextState: order_number     

  order_number:
    transitions:
     -
        condition: order_number
        nextState: order_number
     -
        condition: date
        nextState: date
 
# Here we define the conditions:
conditions:

  date:       '23 < ulx < 60 and text =~ \d{1,2}/\d{1,2}'

  description:'98 < ulx < 400'

  amount:     '400 < ulx < 520'

  order_number: '98 < ulx < 400 and text =~ ^((\d{3})\-)((\d{7})\-)((\d{7})) '

 And the result:
 ./textricator form --config=Chase.yml Chase.pdf Chase.csv
Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: while parsing a block mapping
 in 'reader', line 57, column 5:
        transitions:
        ^
expected <block end>, but found '-'
 in 'reader', line 61, column 5:
        -
        ^

 at [Source: (StringReader); line: 60, column: 27] (through reference chain: io.mfj.textricator.form.config.FormParseConfig["states"])
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:397)
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:356)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1726)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:537)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:419)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1322)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:331)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4524)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3466)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3449)
        at io.mfj.textricator.form.config.FormParseConfigUtil.parseYaml(FormParseConfigUtil.kt:40)
        at io.mfj.textricator.form.config.FormParseConfigUtil.parseYaml(FormParseConfigUtil.kt:30)
        at io.mfj.textricator.cli.TextricatorCli.form(TextricatorCli.kt:170)
        at io.mfj.textricator.cli.TextricatorCli.main(TextricatorCli.kt:91)
Caused by: com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException: while parsing a block mapping
 in 'reader', line 57, column 5:
        transitions:
        ^
expected <block end>, but found '-'
 in 'reader', line 61, column 5:
        -
        ^

 at [Source: (StringReader); line: 60, column: 27]
        at com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException.from(MarkedYAMLException.java:27)
        at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:359)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:403)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1322)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:331)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:540)
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:377)
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:535)
        ... 11 more
Caused by: while parsing a block mapping
 in 'reader', line 57, column 5:
        transitions:
        ^
expected <block end>, but found '-'
 in 'reader', line 61, column 5:
        -
        ^

        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:572)
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
        at org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:168)
        at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:355)
        ... 20 more

**Comment by Gitme76269** [comment]
[Chase - yml.txt](https://github.com/measuresforjustice/textricator/files/5745005/Chase.-.yml.txt)
[Run results.txt](https://github.com/measuresforjustice/textricator/files/5745006/Run.results.txt)

This is my yml and run results

**Comment by eabase** [comment]
@Gitme76269 
Did you get this working? 
I think you might be over complicating things since the Chase data seem to be of table type...

**Comment by Gitme76269** [comment]
Yes, it is resolved

**Comment by eabase** [comment]
@Gitme76269 
Would you mind editing your original post above and add the YAML code within tripple back-ticks? 
Then code highlighting should work.
```YAML
# ```YAML
yamlcode here

```

Trying to resolve a similar issue...so it would be great to be able to read yours.

**Comment by eabase** [comment]
@Gitme76269 
Would you mind sharing your config file? Yours look far simpler...
(The examples given here are way to complicated for practical purposes.)

**Comment by stephenbyrne-mfj** [comment]
[ChaseTestss.pdf](https://github.com/measuresforjustice/textricator/files/6496730/ChaseTestss.pdf)

I removed some of the cut off text from the PDF.

**Comment by stephenbyrne-mfj** [comment]
```yml
extractor: "pdf.pdfbox"

# All measurements are in points. 1 point = 1/72 of an inch.
# x-coordinates are from the left edge of the page.
# y-coordinates are from the top edge of the page.
header:
  default: 108
footer:
   default: 990

maxRowDistance: 2

# Define the output data record.

rootRecordType: date
recordTypes:
  date:
    label: "date"
    valueTypes:
      - date
      - description
      - order_number
      - amount

valueTypes:
  date:
    # In the CSV, use "Employee ID" as the column header instead of "employee".
    label: "Date"
  description:
    label: "Description"
  order_number:
    label: "Order Number"
  amount:
    label: "Amount"
 
# Now we define the finite-state machine
# Let's name the state that our machine starts off with:
initialState: "INIT"

# When each text segment is encountered, each transition for the current state is checked.
states:
  INIT:
    transitions:
     -
      condition: date
      nextState: date

  date:
    startRecord: true # When we enter this stage, we'll create a new "case" record.
    transitions:
      -
        condition: description
        nextState: description  

  description:
    transitions:
      -
        condition: description
        nextState: description
      -
        condition: amount
        nextState: amount

  amount:
    transitions:
       -
         condition: date
         nextState: date
       -
         condition: order_label
         nextState: order_number_label

  order_number_label:
    include: false
    transitions:
       -
         condition: number_label
         nextState: order_number_label
       -
         condition: order_number
         nextState: order_number

  order_number:
    transitions:
      -
        condition: order_number
        nextState: order_number
      -
        condition: date
        nextState: date
 
# Here we define the conditions:
conditions:

  date:       '23 < ulx < 60 and text =~ /\\d{1,2}\/\\d{1,2}/'

  description: '98 < ulx < 400'

  amount:     '400 < ulx < 620'

  order_number: '98 < ulx < 400 and text =~ /^((\\d{3})\\-)((\\d{7})\\-)((\\d{7}))/'

  order_label: '130 < ulx < 140 and text = "Order"'
  number_label: '150 < ulx < 160 and text = "Number"'
```

produces:

```csv
page,Date,Description,Order Number,Amount
1,12/01,AMZN Mktp US Amzn.com/bill WA,111-1111111-1111223,-69.95
1,12/06,BEST BUY CO 00024646 SHEPHERDSVILL KY,,-749.99
1,12/06,THE HOME DEPOT 3402 TILTON NH,,-12.13
```

I escaped special characters in the regular expressions and added handling for "Order Number".
