### ISSUE TITLE
Failing to make a simple example with exactly formatted PDF

### ISSUE THREAD

**Issue by eabase** [measuresforjustice/textricator#19]
Ok, I have tried all examples available, but I am not able to process even the most simple *form* based PDF. 

I have enclosed a test PDF that I was hoping would simplify the **form** processing. It was made from a Word document and I also made a markup version to clarify all the measurements. However, it seem that Textricator is stumbling even on recognizing simple words in **text**-mode. The font used is `12pt Calibri + Bold` on A4 paper size (`595 x 845` pt). 

* Here is the markup PDF:  [xxy_grid_markup.pdf](https://github.com/measuresforjustice/textricator/files/6370552/xxy_grid_markup.pdf)
* Here is the PDF to be processed: [xxy.pdf](https://github.com/measuresforjustice/textricator/files/6370551/xxy.pdf).

Here is a screenshot of the markup file, which I was hoping @stephenbyrne-mfj  could add this to the readme as an example.

![AcroRd32_2021-04-24_22-27-52](https://user-images.githubusercontent.com/52289379/115972068-fb7c5f00-a554-11eb-851b-6bfca59ec044.png)

---

Here is the output:
```bash
# ./textricator.bat form --config=xxy.yml xxy.pdf xxy.csv

Exception in thread "main" java.lang.Exception: Page 1 at "Item" - no valid transition from INIT
        at io.mfj.textricator.form.FsmParser.parse(FsmParser.kt:361)
        at io.mfj.textricator.form.FsmParser.access$parse(FsmParser.kt:35)
        at io.mfj.textricator.form.FsmParser$parse$2.invoke(FsmParser.kt:121)
...
```

The config file is: 

<details>
<summary>Click Here To See!</summary>

```yaml
---

extractor: "pdf.pdfbox"

header:
  default: 100
footer:
   default: 600

maxRowDistance: 2

rootRecordType: item
recordTypes:
  item:
    label: "item"
    valueTypes:
      - item
      - date
      - description
      - order_number
      - quantity
      - price

valueTypes:
  item:
    label: "Item"
  date:
    label: "Date"
  description:
    label: "Description"
  order_number:
    label: "OrderNo"
  quantity:
    label: "Qty"
  price:
    label: "Price"
 
initialState: "INIT"

states:
  INIT:
    transitions:
      -
        condition: item
        nextState: item

  item:
    startRecord: true
    transitions:
      -
        condition: date
        nextState: date  

  date:
    include: true
    transitions:
      -
        condition: description
        nextState: description  

  description:
    include: true
    transitions:
      -
        condition: description
        nextState: description     
      -
        condition: order_number
        nextState: order_number
      -
        condition: quantity
        nextState: quantity

  order_number:
    include: true
    transitions:
      -
        condition: order_number
        nextState: order_number
      -
        condition: quantity
        nextState: quantity

  quantity:
    include: true
    transitions:
      -
        condition: price
        nextState: price

  price:
    include: true
    transitions:
      -
        condition: end
        nextState: end

  end:
    include: false
    transitions:
      -
        condition: any
        nextState: end

conditions:

  item:         '73 < ulx < 110 and text =~ /(\\d)*/'
  date:         '110 < ulx < 181 and text =~ /([0-9\-]*)/'
  description:  '193 < ulx < 366'
#  order_number: '12 <= uly_rel <= 16 and text =~ ^.+/((\d{6})\-)((\d{2}))/'
  order_number: '12 <= uly_rel <= 16 and text =~ ^.+((\d{6})\-)((\d{2}))'
  quantity:     '393 < ulx < 459'
  price:        '459 < ulx < 523'

  end:          'text =~ /(Footer)/'
  any: "1 = 1"

```

</details>

I'd appreciate any good suggestions.

**Comment by mweber55** [comment]
I corrected some parts of your config file, so that it's working with the sample document now:

` 

    extractor: "pdf.pdfbox"

    header:
      default: 100
    footer:
      default: 600

    maxRowDistance: 2

    rootRecordType: item
    recordTypes:
      item:
        label: "item"
        valueTypes:
          - item
          - date
          - description
          - order_number
          - quantity
          - price

    valueTypes:
      item:
        label: "Item"
      date:
        label: "Date"
      description:
        label: "Description"
      order_number:
        label: "OrderNo"
      quantity:
        label: "Qty"
      price:
        label: "Price"
 
    initialState: "INIT"

    states:
      INIT:
        include: false
        transitions:
          -
            condition: item
            nextState: item
          - condition: any
            nextState: INIT

      item:
        startRecord: true
        transitions:
          -
            condition: date
            nextState: date  

      date:
        include: true
        transitions:
          -
            condition: description
            nextState: description  

      description:
        include: true
        transitions:
          -
            condition: description
            nextState: description     
          -
            condition: order_number
            nextState: order_number
          -
            condition: quantity
            nextState: quantity
          -
            condition: item
            nextState: item

      order_number:
        include: true
        transitions:
          -
            condition: order_number
            nextState: order_number
          -
            condition: quantity
            nextState: quantity

      quantity:
        include: true
        transitions:
          - 
            condition: price
            nextState: price

      price:
        include: true
        transitions:
          -
            condition: end
            nextState: end
          - 
            condition: description
            nextState: description
          -
            condition: item
            nextState: item

      end:
        include: false
        transitions:
          -
            condition: any
            nextState: end

    conditions:

      item:         '73 < ulx < 110 and text =~ /(\\d)*/'
      date:         '110 < ulx < 181 and text =~ /([0-9\\-]*)/'
      description:  '193 < ulx < 366'
      order_number: '12 <= uly_rel <= 16 and text =~ /^.+(([0-9]{6})\\-)(([0-9]{2}))/'
      quantity:     '393 < ulx < 459'
      price:        '459 < ulx < 523'

      end:          'text =~ /(Footer)/'
      any: "1 = 1"

`   

Feel free to ask for any detail of the diffs, if necessary.

**Comment by eabase** [comment]
@mweber55 
Wow! That actually worked, even with the ASM warning that I though was preventing the output.

Almost party, but the `OrderNo` end up in the `Description` column...
But at last a great start, thank you! :100: 

![EXCEL_2021-05-17_21-05-20](https://user-images.githubusercontent.com/52289379/118543146-959e8400-b75c-11eb-9457-f9ca213906aa.png)

**Comment by mweber55** [comment]
@eabase You're welcome.
 I missed the order number, thought description could be multiline. To catch the orderno, use something like that:
``` yaml
    extractor: "pdf.pdfbox"

    header:
      default: 100
    footer:
      default: 600

    maxRowDistance: 2

    rootRecordType: item
    recordTypes:
      item:
        label: "item"
        valueTypes:
          - item
          - date
          - description
          - order_number
          - quantity
          - price

    valueTypes:
      item:
        label: "Item"
      date:
        label: "Date"
      description:
        label: "Description"
      order_number:
        label: "OrderNo"
      quantity:
        label: "Qty"
      price:
        label: "Price"
 
    initialState: "INIT"

    states:
      INIT:
        include: false
        transitions:
          -
            condition: item
            nextState: item
          # stay in INIT until first item is reached 
          - condition: any
            nextState: INIT

      item:
        startRecord: true
        transitions:
          -
            condition: date
            nextState: date  

      date:
        include: true
        transitions:
          -
            condition: description
            nextState: description  

      description:
        include: true
        transitions:
          -
            condition: description
            nextState: description     
          -
            condition: order_number_title
            nextState: order_number_title
          -
            condition: quantity
            nextState: quantity
          -
            condition: item
            nextState: item

      order_number_title:
        include: false
        transitions:
          -
            condition: order_number
            nextState: order_number

      order_number:
        include: true
        transitions:
          -
            condition: order_number
            nextState: order_number
          -
            condition: quantity
            nextState: quantity
          -
            condition: item
            nextState: item

      quantity:
        include: true
        transitions:
          - 
            condition: price
            nextState: price

      price:
        include: true
        transitions:
          -
            condition: end
            nextState: end
          - 
            condition: order_number_title
            nextState: order_number_title
          -
            condition: item
            nextState: item

      end:
        include: false
        transitions:
          -
            condition: any
            nextState: end

    conditions:

      item:         '73 < ulx < 110 and text =~ /(\\d)*/'
      date:         '110 < ulx < 181 and text =~ /([0-9\\-]*)/'
      description:  '193 < ulx < 366'
      order_number: '245 <= ulx <= 300 and text =~ /^([0-9]{6})-([0-9]{2})/'
      order_number_title: 'text = "OrderNo:" and 195 <= ulx <= 220'
      quantity:     '393 < ulx < 459'
      price:        '459 < ulx < 523'

      end:          'text =~ /(Footer)/'
      any: "1 = 1"
```
